# Generated by Django 3.1.4 on 2020-12-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0002_auto_20201220_2218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employeeapi_employee',
            new_name='Employee',
        ),
    ]
